# Generated by Django 4.0 on 2022-08-14 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import restrant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourtsBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, default='No Address', null=True)),
                ('postal_code', models.CharField(blank=True, default='No Postal Code', max_length=50, null=True)),
                ('symbl', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, default='No Area', max_length=50, null=True)),
                ('terms', models.BooleanField(blank=True, default=True, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.FileField(null=True, upload_to=restrant.models.restaurant_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('trader_payment', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_profile_id', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_aut', models.TextField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(blank=True, max_length=50, null=True)),
                ('table_code', models.CharField(blank=True, max_length=250, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.branchesprofile')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restaurantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.branchesprofile')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.courtsbranches')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restaurantprofile')),
            ],
        ),
        migrations.AddField(
            model_name='branchesprofile',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restaurantprofile'),
        ),
        migrations.AddField(
            model_name='branchesprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
