# Generated by Django 4.0 on 2022-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='courtsbranches',
            name='code',
            field=models.PositiveIntegerField(blank=True, max_length=250, null=True),
        ),
    ]
