# Generated by Django 4.0 on 2022-08-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0003_courtsbranches_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsbranches',
            name='tables',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
