# Generated by Django 4.0 on 2022-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0004_alter_courtsbranches_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranches',
            name='table_code',
            field=models.PositiveIntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantbranches',
            name='table_no',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
