# Generated by Django 4.0 on 2022-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0007_alter_restaurantbranches_table_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranches',
            name='table_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
