# Generated by Django 4.0 on 2022-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0009_branchesprofile_service_restaurantprofile_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchesprofile',
            name='srv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
