# Generated by Django 4.0 on 2022-08-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0011_restaurantbranches_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsbranches',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantbranches',
            name='table_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
