# Generated by Django 4.0 on 2022-08-17 22:50

import django.core.validators
from django.db import migrations, models
import restrant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0012_alter_courtsbranches_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsbranches',
            name='qr_code',
            field=models.FileField(null=True, upload_to=restrant.models.branch_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
