# Generated by Django 4.0 on 2022-08-17 22:52

import django.core.validators
from django.db import migrations, models
import restrant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0013_courtsbranches_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsbranches',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to=restrant.models.branch_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='restaurantbranches',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to=restrant.models.branch_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
