# Generated by Django 4.0 on 2022-08-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0015_branchesprofile_is_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('cret_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.branchesprofile')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restaurantprofile')),
            ],
        ),
    ]
