# Generated by Django 4.0 on 2022-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0016_ressupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsbranches',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
