# Generated by Django 4.0 on 2022-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0017_alter_courtsbranches_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='vat',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
