# Generated by Django 4.0 on 2022-08-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0020_countrycode_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restrant.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='period',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
