# Generated by Django 4.0 on 2022-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0021_restaurantprofile_plan_subscriptionplan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
