# Generated by Django 4.0 on 2022-08-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0022_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorders',
            name='c_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorders',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorders',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorders',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
