# Generated by Django 4.0 on 2022-08-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0024_countrycode_bg_pln_countrycode_elit_pln_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='bg_period',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='countrycode',
            name='elit_period',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='countrycode',
            name='go_period',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='countrycode',
            name='strt_period',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
