# Generated by Django 4.0 on 2022-08-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0025_countrycode_bg_period_countrycode_elit_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorders',
            name='period',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorders',
            name='until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
