# Generated by Django 4.0 on 2022-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0027_subscriptionorders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
