# Generated by Django 4.0 on 2022-08-16 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0010_branchesprofile_srv'),
        ('cart', '0002_alter_orderproducts_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restaurantprofile'),
        ),
    ]
