# Generated by Django 4.0 on 2022-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orders_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_rate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='tran_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
