# Generated by Django 4.0 on 2022-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orders_is_rate_orders_rate_orders_tran_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
