# Generated by Django 4.0 on 2022-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_orders_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
