# Generated by Django 4.0 on 2022-08-22 10:23

import cart.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_orders_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to=cart.models.qrcode_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
