# Generated by Django 4.0 on 2022-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_branchrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifuser',
            name='body',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='notifuser',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
