# Generated by Django 4.0 on 2022-08-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_webcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
