# Generated by Django 4.0 on 2022-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_ordertracking_end_date_ordertracking_process_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchrate',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchrate',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
