# Generated by Django 4.0 on 2022-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_branchrate_end_date_branchrate_process_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchrate',
            name='end_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchrate',
            name='process_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='end_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='process_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
