# Generated by Django 4.0 on 2022-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_ordertracking_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
