# Generated by Django 4.0 on 2022-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_branchrate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrate',
            name='end_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchrate',
            name='process_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='end_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='process_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='start_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
