# Generated by Django 4.0 on 2022-08-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrant', '0028_restaurantprofile_until_date'),
        ('tracking', '0012_alter_branchrate_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchrate',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrant.restaurantprofile'),
        ),
    ]
