# Generated by Django 4.0 on 2022-08-14 12:38

import django.core.validators
from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuscategory',
            name='photo',
            field=models.FileField(null=True, upload_to=menu.models.cat_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
