# Generated by Django 4.0 on 2022-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuscategory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuscategory',
            name='name_la',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menusitems',
            name='describe_la',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menusitems',
            name='name_la',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
