# Generated by Django 4.0 on 2022-08-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuscategory_name_la_menusitems_describe_la_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchesmenusitems',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menusname'),
        ),
        migrations.AlterField(
            model_name='branchmenu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menusname'),
        ),
    ]
